{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexurbis-manager.fullname" . }}-redis
  labels:
    {{- include "nexurbis-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "nexurbis-manager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "nexurbis-manager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)", "--appendonly", "yes"]
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nexurbis-manager.fullname" . }}-redis-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexurbis-manager.fullname" . }}-redis-pvc
  labels:
    {{- include "nexurbis-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | default "2Gi" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexurbis-manager.fullname" . }}-redis
  labels:
    {{- include "nexurbis-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      name: redis
  selector:
    {{- include "nexurbis-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}

{{- if .Values.extraManifests }}
{{- range .Values.extraManifests }}
---
{{ tpl . $ }}
{{- end }}
{{- end }}