apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timescale.fullname" . }}
  labels:
    {{- include "timescale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "timescale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timescale.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              {{- if .Values.postgresql.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: {{ .Values.postgresql.existingSecretPasswordKey | default "password" }}
              {{- else }}
              value: {{ .Values.postgresql.password | quote }}
              {{- end }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "timescale.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}