apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescale.fullname" . }}
  labels:
    {{- include "timescale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "timescale.selectorLabels" . | nindent 4 }}