replicaCount: 1

image:
  repository: apache/apisix
  pullPolicy: IfNotPresent
  tag: "3.9.1-debian"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

config:
  orionHost: "scorpio"
  orionPort: 9090
  mintakaHost: "mintaka"
  mintakaPort: 8080
  keycloakClientId: "apisix-pep"
  keycloakClientSecret: ""
  keycloakDiscoveryUrl: "http://keycloak-keycloakx-http:80/realms/fiware-server/.well-known/openid-configuration"