apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL using official image
type: application
version: 0.1.0
appVersion: "15-alpine"
maintainers:
  - name: platform-team
    email: platform@mark-frost.sk
