#!/usr/bin/env bash
set -euo pipefail

if [ ! -f pub-cert.pem ]; then
    echo "Error: pub-cert.pem not found. Run: kubeseal --fetch-cert > pub-cert.pem"
    exit 1
fi

if [ ! -f .secrets.env ]; then
    echo "Error: .secrets.env not found. Please copy .secrets.env.example to .secrets.env and fill it out."
    exit 1
fi

# Load environment variables
source .secrets.env

echo "Sealing secrets..."

seal() {
    local namespace="$1"
    local name="$2"
    local value="$3"
    echo -n "$value" | kubeseal --raw --namespace "$namespace" --name "$name" --cert pub-cert.pem
}

NAMESPACE="smartcity"

echo "  - keycloak db"
KC_DB_ENC=$(seal "$NAMESPACE" "keycloak-db-auth" "$KC_DB_PASSWORD")

echo "  - keycloak admin"
KC_ADM_U_ENC=$(seal "$NAMESPACE" "keycloak-admin-creds" "$KC_ADMIN_USER")
KC_ADM_P_ENC=$(seal "$NAMESPACE" "keycloak-admin-creds" "$KC_ADMIN_PASSWORD")

echo "  - platform extra manifests (Oauth & Passwords)"
GRAFANA_OAUTH_ENC=$(seal "$NAMESPACE" "grafana-oauth" "$GRAFANA_OAUTH_SECRET")
MQTT_EXPLORER_OAUTH_ENC=$(seal "$NAMESPACE" "mqtt-explorer-oauth2" "$MQTT_EXPLORER_OAUTH_SECRET")
NODE_RED_OAUTH_ENC=$(seal "$NAMESPACE" "node-red-oauth2" "$NODE_RED_OAUTH_SECRET")
CB_PEP_ENC=$(seal "$NAMESPACE" "cb-pep-credentials" "$CB_PEP_SECRET")
NGSILD_OAUTH_ENC=$(seal "$NAMESPACE" "ngsild-oauth" "$NGSILD_OAUTH_SECRET")
NODE_RED_NGSILD_ENC=$(seal "$NAMESPACE" "node-red-ngsild" "$NODE_RED_NGSILD_SECRET")
CONSUMER_USER_ENC=$(seal "$NAMESPACE" "consumer-user-credentials" "$CONSUMER_USER_PASSWORD")
ADMIN_USER_ENC=$(seal "$NAMESPACE" "admin-user-credentials" "$ADMIN_USER_PASSWORD")
EMQX_DASHBOARD_OAUTH_ENC=$(seal "$NAMESPACE" "emqx-dashboard-oauth2" "$EMQX_DASHBOARD_OAUTH_SECRET")
NEXURBIS_MANAGER_OAUTH_ENC=$(seal "$NAMESPACE" "nexurbis-manager-oauth2" "$NEXURBIS_MANAGER_OAUTH_SECRET")
TSDB_ENC=$(seal "$NAMESPACE" "tsdb-credentials" "$TSDB_PASSWORD")
NEXURBIS_DB_ENC=$(seal "$NAMESPACE" "nexurbis-db-credentials" "$NEXURBIS_DB_PASSWORD")
EMQX_DASHBOARD_ENC=$(seal "$NAMESPACE" "emqx-dashboard-credentials" "$EMQX_DASHBOARD_PASSWORD")
MONGODB_ENC=$(seal "$NAMESPACE" "mongodb-iotagent" "$MONGODB_PASSWORD")
POSTGRES_ENC=$(seal "$NAMESPACE" "postgres-auth" "$POSTGRES_PASSWORD")

cat <<EOF > platform/secrets.yaml
# THIS FILE IS AUTOGENERATED BY scripts/seal.sh
# DO NOT EDIT MANUALLY!

applications:
  keycloak-db:
    values:
      sealedSecret:
        encryptedPassword: "$KC_DB_ENC"
  keycloak:
    values:
      secrets:
        admin-creds:
          sealed: true
          encryptedData:
            user: "$KC_ADM_U_ENC"
            password: "$KC_ADM_P_ENC"
      sealedSecrets:
        grafanaOauth: "$GRAFANA_OAUTH_ENC"
        mqttExplorerOauth: "$MQTT_EXPLORER_OAUTH_ENC"
        nodeRedOauth: "$NODE_RED_OAUTH_ENC"
        cbPep: "$CB_PEP_ENC"
        ngsildOauth: "$NGSILD_OAUTH_ENC"
        nodeRedNgsild: "$NODE_RED_NGSILD_ENC"
        consumerUser: "$CONSUMER_USER_ENC"
        adminUser: "$ADMIN_USER_ENC"
        emqxDashboardOauth: "$EMQX_DASHBOARD_OAUTH_ENC"
        nexurbisManagerOauth: "$NEXURBIS_MANAGER_OAUTH_ENC"
        tsdb: "$TSDB_ENC"
        nexurbisDb: "$NEXURBIS_DB_ENC"
        emqxDashboard: "$EMQX_DASHBOARD_ENC"
        mongodb: "$MONGODB_ENC"
        postgres: "$POSTGRES_ENC"
EOF

echo "✅ Successfully generated platform/secrets.yaml"