#!/usr/bin/env bash
set -euo pipefail

if [ ! -f pub-cert.pem ]; then
    echo "Error: pub-cert.pem not found. Run: kubeseal --fetch-cert > pub-cert.pem"
    exit 1
fi

if [ ! -f .secrets.env ]; then
    echo "Error: .secrets.env not found. Please copy .secrets.env.example to .secrets.env and fill it out."
    exit 1
fi

# Load environment variables
source .secrets.env

echo "Sealing secrets..."

seal() {
    local namespace="$1"
    local name="$2"
    local value="$3"
    echo -n "$value" | kubeseal --raw --namespace "$namespace" --name "$name" --cert pub-cert.pem
}

NAMESPACE="smartcity"

echo "  - wordpress"
WP_M_ROOT_ENC=$(seal "$NAMESPACE" "wordpress-wordpress-credentials" "$WP_MARIADB_ROOT_PASSWORD")
WP_M_ENC=$(seal "$NAMESPACE" "wordpress-wordpress-credentials" "$WP_MARIADB_PASSWORD")
WP_W_ENC=$(seal "$NAMESPACE" "wordpress-wordpress-credentials" "$WP_WORDPRESS_PASSWORD")
WP_O_ENC=$(seal "$NAMESPACE" "wordpress-wordpress-credentials" "$WP_OAUTH_CLIENT_SECRET")

echo "  - wordpress-marek-mraz"
MM_M_ROOT_ENC=$(seal "$NAMESPACE" "wordpress-marek-mraz-wordpress-credentials" "$WP_MM_MARIADB_ROOT_PASSWORD")
MM_M_ENC=$(seal "$NAMESPACE" "wordpress-marek-mraz-wordpress-credentials" "$WP_MM_MARIADB_PASSWORD")
MM_W_ENC=$(seal "$NAMESPACE" "wordpress-marek-mraz-wordpress-credentials" "$WP_MM_WORDPRESS_PASSWORD")
MM_O_ENC=$(seal "$NAMESPACE" "wordpress-marek-mraz-wordpress-credentials" "$WP_MM_OAUTH_CLIENT_SECRET")

echo "  - keycloak db"
KC_DB_ENC=$(seal "$NAMESPACE" "keycloak-db-auth" "$KC_DB_PASSWORD")

echo "  - keycloak admin"
KC_ADM_U_ENC=$(seal "$NAMESPACE" "keycloak-admin-creds" "$KC_ADMIN_USER")
KC_ADM_P_ENC=$(seal "$NAMESPACE" "keycloak-admin-creds" "$KC_ADMIN_PASSWORD")

echo "  - keycloak oauth"
KC_OA_WP_ENC=$(seal "$NAMESPACE" "keycloak-oauth-secrets" "$WP_OAUTH_CLIENT_SECRET")
KC_OA_MM_ENC=$(seal "$NAMESPACE" "keycloak-oauth-secrets" "$WP_MM_OAUTH_CLIENT_SECRET")

cat <<EOF > platform/secrets.yaml
# THIS FILE IS AUTOGENERATED BY scripts/seal.sh
# DO NOT EDIT MANUALLY!

applications:
  keycloak-db:
    values:
      sealedSecret:
        encryptedPassword: "$KC_DB_ENC"
  keycloak:
    values:
      secrets:
        admin-creds:
          sealed: true
          encryptedData:
            user: "$KC_ADM_U_ENC"
            password: "$KC_ADM_P_ENC"
        oauth-secrets:
          sealed: true
          encryptedData:
            wordpress: "$KC_OA_WP_ENC"
            wordpress-marek-mraz: "$KC_OA_MM_ENC"
  wordpress:
    values:
      sealedSecret:
        encryptedData:
          mariadb-root-password: "$WP_M_ROOT_ENC"
          mariadb-password: "$WP_M_ENC"
          wordpress-password: "$WP_W_ENC"
          oauth-client-secret: "$WP_O_ENC"
  wordpress-marek-mraz:
    values:
      sealedSecret:
        encryptedData:
          mariadb-root-password: "$MM_M_ROOT_ENC"
          mariadb-password: "$MM_M_ENC"
          wordpress-password: "$MM_W_ENC"
          oauth-client-secret: "$MM_O_ENC"
EOF

echo "✅ Successfully generated platform/secrets.yaml"