{{- range $name, $data := .Values.secretsData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
{{- range $key, $value := $data }}
{{- if eq $value "GENERATE" }}
  {{ $key }}: {{ randAlphaNum 16 | quote }}
{{- else if eq $value "GENERATE_HEX" }}
  {{ $key }}: {{ randAlphaNum 32 | lower | quote }}
{{- else }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- end }}