{{- range $name, $data := .Values.secretsData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
{{ toYaml $data | indent 2 }}
---
{{- end }}