{{- range $appName, $appConfig := .Values.applications }}
{{- if default true $appConfig.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ default 0 $appConfig.syncWave | quote }}
spec:
  project: default
  source:
    repoURL: {{ default $.Values.global.repoURL $appConfig.repoURL | quote }}
    targetRevision: {{ default $.Values.global.targetRevision $appConfig.targetRevision | quote }}
    {{- if $appConfig.chart }}
    chart: {{ $appConfig.chart }}
    {{- else }}
    path: {{ $appConfig.path }}
    {{- end }}
    {{- if $appConfig.values }}
    helm:
      values: |
        {{- tpl (toYaml $appConfig.values) $ | nindent 8 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ default $appName $appConfig.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
{{- end }}
{{- end }}