{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scorpioBroker-aaio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        {{- include "scorpioBroker-aaio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
    spec:
      containers:
      - image: zookeeper:3.8
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
          protocol: TCP
        volumeMounts:
          - name: zookeeper-data
            mountPath: /data
          - name: zookeeper-datalog
            mountPath: /datalog
      volumes:
        - name: zookeeper-data
          {{- if .Values.kafka.zookeeper.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper-data-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: zookeeper-datalog
          {{- if .Values.kafka.zookeeper.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper-datalog-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.kafka.zookeeper.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper-data-pvc
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.zookeeper.persistence.size | default "2Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper-datalog-pvc
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.zookeeper.persistence.size | default "2Gi" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scorpioBroker-aaio.fullname" . }}-zookeeper
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
    {{- include "scorpioBroker-aaio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
{{- end }}