secretsData:
  grafana-admin-user:
    admin-user: "fiwareAdmin"
    admin-password: "fiwareAdminPassword123"
  keycloak-admin-credentials:
    username: "admin"
    password: "keycloakAdminPassword123"
  admin-user-credentials:
    password: "adminUserPassword123"
  consumer-user-credentials:
    password: "consumerUserPassword123"
  tsdb-credentials:
    password: "tsdbPassword123"
  tsdb-password:
    password: "tsdbPassword123"
  grafana-oauth:
    client-secret: "grafana-oauth-secret-123"
  mqtt-explorer-oauth2:
    client-id: "mqtt-explorer"
    client-secret: "mqtt-explorer-oauth-secret-123"
    cookie-secret: "encrypted-cookie-secret-12345678"
  emqx-dashboard-oauth2:
    client-id: "emqx-dashboard"
    client-secret: "emqx-dashboard-oauth-secret-123"
    cookie-secret: "encrypted-cookie-secret-12345678"
  cb-pep-credentials:
    client-secret: "cb-pep-oauth-secret-123"
  ngsild-oauth:
    client-secret: "ngsild-oauth-secret-123"
  node-red-oauth2:
    client-id: "node-red"
    client-secret: "node-red-oauth-secret-123"
    cookie-secret: "encrypted-cookie-secret-12345678"
  node-red-ngsild:
    client-secret: "node-red-ngsild-oauth-secret-123"