secretsData:
  grafana-admin-user:
    admin-user: "fiwareAdmin"
    admin-password: "GENERATE"
  keycloak-admin-credentials:
    username: "admin"
    password: "GENERATE"
  keycloak-db-credentials:
    postgres-password: "GENERATE"
    password: "GENERATE"
  admin-user-credentials:
    password: "GENERATE"
  consumer-user-credentials:
    password: "GENERATE"
  tsdb-credentials:
    password: "GENERATE"
  tsdb-password:
    password: "GENERATE"
  grafana-oauth:
    client-secret: "GENERATE"
  mqtt-explorer-oauth2:
    client-id: "mqtt-explorer"
    client-secret: "GENERATE"
    cookie-secret: "GENERATE_HEX"
  emqx-dashboard-oauth2:
    client-id: "emqx-dashboard"
    client-secret: "GENERATE"
    cookie-secret: "GENERATE_HEX"
  cb-pep-credentials:
    client-secret: "GENERATE"
  ngsild-oauth:
    client-secret: "GENERATE"
  node-red-oauth2:
    client-id: "node-red"
    client-secret: "GENERATE"
    cookie-secret: "GENERATE_HEX"
  node-red-ngsild:
    client-secret: "GENERATE"
  emqx-dashboard-credentials:
    EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
    EMQX_DASHBOARD__DEFAULT_PASSWORD: "GENERATE"
  nexurbis-manager-oauth2:
    client-id: "nexurbis-manager"
    client-secret: "GENERATE"
  nexurbis-db-credentials:
    password: "GENERATE"